title: Shuwei's blog 自留地
description: Shuwei's personal blog
author: Fang Shuwei
logo: http://aboutashu.com/hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/fsw0723
about:
disqus_shortname: fsw0723
google_analytics:
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-comments
    - text: Resume
      url: '/resume'
      icon: fa-graduation-cap
    - text: Github
      url: https://github.com/fsw0723
      icon: fa-github
    - text: RSS
      url: /feed.xml
      icon: fa-feed
      target: _blank
      
social:
    - icon: fa-facebook
      link: 'https://www.facebook.com/shuweifang'
    - icon: fa-linkedin
      link: 'https://www.linkedin.com/in/shuwei-fang-b61aaa69'

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "http://localhost:4000"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist