# Jekyll configuration

name: My blog 自留地
description: Shuwei's personal blog

# url is currently only used only for the RSS feed in feed.xml
url: http://fsw0723.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# This can be '' to hide the Github nav button
github: 'https://github.com/fsw0723'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: true

permalink: /:year/:month/:title
paginate: 3

highlighter: pygments
markdown: kramdown

exclude: ['README.md', 'LICENSE']
